CREATE TABLE my_user (ID BIGINT NOT NULL, CONTACTS BYTEA, IMAGEIDS BYTEA, PASSWORD VARCHAR(255), UPLOADS BIGINT, USERNAME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE my_image (ID BIGINT NOT NULL, COMMENT VARCHAR(255), NAME VARCHAR(255), PATH VARCHAR(255), UPLOADTIME BYTEA, VIEWSTATUS BOOLEAN, PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
